version: '3.7'

services:

  cache:
    image: redis:latest
    volumes:
      - ./data/cache:/data/

  db:
    image: postgres:14.5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  message_broker:
    image: rabbitmq:latest
    ports:
      - "5672:5672"

  worker:
    build: .
    command: celery -A core worker -l info
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PYTHONPATH=/code/backend
      - DJANGO_SETTINGS_MODULE=backend.core.settings.prod
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "celery", "status"]
      interval: 10s
      retries: 5
      timeout: 5s
    depends_on:
      - message_broker
      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0:8000
    ports:
      - "8000:8000" 
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=backend.core.settings.prod
      - POSTGRES_DB=postgres  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache
      - message_broker
